# -- Theme Options --
# Color scheme - choose from: blowfish, ocean, forest, autumn, fire, neon, slate, etc.
colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

# Features
enableSearch = true
enableCodeCopy = true
replyByEmail = false

# Performance
disableImageOptimization = false
fingerprintAlgorithm = "sha512"

[header]
layout = "fixed-fill"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = false

[article]
showDate = true
showViews = false
showLikes = false
showAuthor = true
showHero = true
heroStyle = "thumbAndBackground"
layoutBackgroundBlur = true
showBreadcrumbs = true
showDraftLabel = true
showHeadingAnchors = true
showPagination = true
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showWordCount = true
sharingLinks = ["twitter", "facebook", "linkedin", "reddit", "email"]
showZenMode = true

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
showBreadcrumbs = true
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[taxonomy]
showTermCount = true
showHero = false
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = false
heroStyle = "background"
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = true
cardViewScreenWidth = false