baseURL = 'https://samzone.com/'
languageCode = 'zh-TW'
title = 'SAM ZONE - Sam Tsai 的個人部落格'
theme = "blowfish"

# Content settings
[pagination]
pagerSize = 10
summaryLength = 200
hasCJKLanguage = true

# SEO and Social
enableRobotsTXT = true
enableGitInfo = true

# RSS
[services.rss]
limit = 20

# Markup settings for better content rendering
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = false
    noClasses = false

# Taxonomy settings
[taxonomies]
  category = 'categories'
  tag = 'tags'
  topic = 'topics'
  series = 'series'

# Sitemap configuration
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

# Privacy settings
[privacy]
  [privacy.youtube]
    privacyEnhanced = true
